"""
PAIMANA - Database Seeder
Seeds SQLite database with 18 highly realistic Indian infrastructure projects
spanning High-Speed Rail, Expressways, Metros, Bridges, Mega Airports, Irrigation, Urban Water & Solar Utilities.
Includes realistic mixtures of LOW, MEDIUM, HIGH, and CRITICAL risk profiles.
"""

from .database import SessionLocal, engine, Base
from .models import Project, Alert, AnalysisLog
from .services.prediction_service import prediction_engine
import json
import datetime

SAMPLE_PROJECTS = [
    # --- 1. CRITICAL PROJECTS (3+ projects) ---
    {
        "code": "PRJ-IND-MET-003",
        "name": "Pune Metro Line 3 Extension (Hinjawadi - Shivajinagar)",
        "category": "Metro",
        "location": "Maharashtra",
        "executing_agency": "Pune Metropolitan Region Development Authority (PMRDA)",
        "contractor_name": "Tata-Siemens JV & Afcons",
        "project_cost": 8313.0,
        "planned_duration_months": 42,
        "start_date": "2023-01-15",
        "target_completion_date": "2026-07-15",
        "planned_progress": 72.0,
        "actual_progress": 46.5,
        "expenditure_percentage": 68.2,
        "resource_availability": 52.0,
        "material_availability": 48.0,
        "workforce_availability": 55.0,
        "contractor_performance": 51.0,
        "delay_days": 135,
        "milestone_completion_rate": 50.0,
        "change_requests": 6,
        "weather_impact": 5.8,
        "previous_delay_count": 3,
        "risk_history": 7.5
    },
    {
        "code": "PRJ-IND-RAI-007",
        "name": "Rishikesh - Karnaprayag Himalayan Railway Link (Tunnel Package 4)",
        "category": "Railway",
        "location": "Uttarakhand",
        "executing_agency": "Rail Vikas Nigam Limited (RVNL)",
        "contractor_name": "L&T Geostructural Engineering",
        "project_cost": 16200.0,
        "planned_duration_months": 60,
        "start_date": "2022-04-10",
        "target_completion_date": "2027-04-10",
        "planned_progress": 65.0,
        "actual_progress": 38.0,
        "expenditure_percentage": 62.0,
        "resource_availability": 45.0,
        "material_availability": 42.0,
        "workforce_availability": 50.0,
        "contractor_performance": 48.0,
        "delay_days": 180,
        "milestone_completion_rate": 42.0,
        "change_requests": 8,
        "weather_impact": 8.5,
        "previous_delay_count": 4,
        "risk_history": 8.2
    },
    {
        "code": "PRJ-IND-IRR-011",
        "name": "Polavaram National Irrigation Dam - Left Main Canal Package",
        "category": "Irrigation",
        "location": "Andhra Pradesh",
        "executing_agency": "Water Resources Department / PPA",
        "contractor_name": "Megha Engineering & Infrastructures Ltd (MEIL)",
        "project_cost": 12500.0,
        "planned_duration_months": 54,
        "start_date": "2021-11-01",
        "target_completion_date": "2026-05-01",
        "planned_progress": 85.0,
        "actual_progress": 54.0,
        "expenditure_percentage": 78.5,
        "resource_availability": 48.0,
        "material_availability": 50.0,
        "workforce_availability": 46.0,
        "contractor_performance": 45.0,
        "delay_days": 195,
        "milestone_completion_rate": 45.0,
        "change_requests": 7,
        "weather_impact": 7.2,
        "previous_delay_count": 5,
        "risk_history": 8.8
    },
    {
        "code": "PRJ-IND-RAI-018",
        "name": "Bilaspur - Manali - Leh Strategic Strategic Rail Grid",
        "category": "Railway",
        "location": "Himachal Pradesh",
        "executing_agency": "Northern Railway & BRO",
        "contractor_name": "IRCON International",
        "project_cost": 22400.0,
        "planned_duration_months": 84,
        "start_date": "2022-09-01",
        "target_completion_date": "2029-09-01",
        "planned_progress": 42.0,
        "actual_progress": 19.5,
        "expenditure_percentage": 38.0,
        "resource_availability": 40.0,
        "material_availability": 38.0,
        "workforce_availability": 42.0,
        "contractor_performance": 49.0,
        "delay_days": 150,
        "milestone_completion_rate": 35.0,
        "change_requests": 9,
        "weather_impact": 9.2,
        "previous_delay_count": 3,
        "risk_history": 8.0
    },

    # --- 2. HIGH RISK PROJECTS (4+ projects) ---
    {
        "code": "PRJ-IND-HWY-002",
        "name": "Bharatmala Coastal Corridor - Vizag to Chennai Section",
        "category": "Highway",
        "location": "Tamil Nadu",
        "executing_agency": "National Highways Authority of India (NHAI)",
        "contractor_name": "GVR Infra Projects",
        "project_cost": 4650.0,
        "planned_duration_months": 36,
        "start_date": "2023-03-01",
        "target_completion_date": "2026-03-01",
        "planned_progress": 78.0,
        "actual_progress": 58.5,
        "expenditure_percentage": 71.0,
        "resource_availability": 62.0,
        "material_availability": 58.0,
        "workforce_availability": 65.0,
        "contractor_performance": 58.0,
        "delay_days": 85,
        "milestone_completion_rate": 60.0,
        "change_requests": 4,
        "weather_impact": 5.2,
        "previous_delay_count": 2,
        "risk_history": 6.5
    },
    {
        "code": "PRJ-IND-MET-005",
        "name": "Patna Metro Corridor 1 (Danapur to Khemnichak)",
        "category": "Metro",
        "location": "Bihar",
        "executing_agency": "Delhi Metro Rail Corp (DMRC) / PMRCL",
        "contractor_name": "NCC - J.Kumar Infra JV",
        "project_cost": 6120.0,
        "planned_duration_months": 48,
        "start_date": "2022-10-01",
        "target_completion_date": "2026-10-01",
        "planned_progress": 68.0,
        "actual_progress": 49.0,
        "expenditure_percentage": 63.5,
        "resource_availability": 60.0,
        "material_availability": 62.0,
        "workforce_availability": 58.0,
        "contractor_performance": 62.0,
        "delay_days": 95,
        "milestone_completion_rate": 58.0,
        "change_requests": 5,
        "weather_impact": 4.8,
        "previous_delay_count": 2,
        "risk_history": 6.8
    },
    {
        "code": "PRJ-IND-BRG-009",
        "name": "Brahmaputra 6-Lane Extradosed Bridge (Guwahati - North Guwahati)",
        "category": "Bridge",
        "location": "Assam",
        "executing_agency": "Guwahati Metropolitan Development Authority (GMDA)",
        "contractor_name": "SP Singla Constructions",
        "project_cost": 2608.0,
        "planned_duration_months": 48,
        "start_date": "2022-06-01",
        "target_completion_date": "2026-06-01",
        "planned_progress": 70.0,
        "actual_progress": 52.0,
        "expenditure_percentage": 66.0,
        "resource_availability": 64.0,
        "material_availability": 59.0,
        "workforce_availability": 66.0,
        "contractor_performance": 64.0,
        "delay_days": 80,
        "milestone_completion_rate": 62.0,
        "change_requests": 4,
        "weather_impact": 7.6,
        "previous_delay_count": 2,
        "risk_history": 6.2
    },
    {
        "code": "PRJ-IND-WAT-013",
        "name": "Jal Jeevan Mission Bundelkhand Rural Piped Water Supply",
        "category": "Water Supply",
        "location": "Uttar Pradesh",
        "executing_agency": "State Water & Sanitation Mission (SWSM)",
        "contractor_name": "PNC Infratech Ltd",
        "project_cost": 3150.0,
        "planned_duration_months": 30,
        "start_date": "2023-06-01",
        "target_completion_date": "2025-12-01",
        "planned_progress": 82.0,
        "actual_progress": 64.0,
        "expenditure_percentage": 76.0,
        "resource_availability": 65.0,
        "material_availability": 60.0,
        "workforce_availability": 68.0,
        "contractor_performance": 65.0,
        "delay_days": 65,
        "milestone_completion_rate": 66.0,
        "change_requests": 3,
        "weather_impact": 3.8,
        "previous_delay_count": 2,
        "risk_history": 5.9
    },

    # --- 3. MEDIUM RISK PROJECTS (4+ projects) ---
    {
        "code": "PRJ-IND-HWY-001",
        "name": "Delhi - Mumbai Expressway (Package 4: Vadodara - Kim Spur)",
        "category": "Highway",
        "location": "Gujarat",
        "executing_agency": "National Highways Authority of India (NHAI)",
        "contractor_name": "Dilip Buildcon Ltd",
        "project_cost": 5400.0,
        "planned_duration_months": 36,
        "start_date": "2023-05-01",
        "target_completion_date": "2026-05-01",
        "planned_progress": 62.0,
        "actual_progress": 54.0,
        "expenditure_percentage": 58.0,
        "resource_availability": 76.0,
        "material_availability": 74.0,
        "workforce_availability": 78.0,
        "contractor_performance": 73.0,
        "delay_days": 35,
        "milestone_completion_rate": 75.0,
        "change_requests": 2,
        "weather_impact": 3.2,
        "previous_delay_count": 1,
        "risk_history": 4.1
    },
    {
        "code": "PRJ-IND-MET-006",
        "name": "Mumbai Metro Line 4 (Wadala - Kasarvadavali Elevated Corridor)",
        "category": "Metro",
        "location": "Maharashtra",
        "executing_agency": "Mumbai Metropolitan Region Development Authority (MMRDA)",
        "contractor_name": "Reliance Infrastructure - Astaldi JV",
        "project_cost": 14549.0,
        "planned_duration_months": 54,
        "start_date": "2022-08-15",
        "target_completion_date": "2027-02-15",
        "planned_progress": 55.0,
        "actual_progress": 47.0,
        "expenditure_percentage": 52.0,
        "resource_availability": 74.0,
        "material_availability": 72.0,
        "workforce_availability": 76.0,
        "contractor_performance": 71.0,
        "delay_days": 42,
        "milestone_completion_rate": 72.0,
        "change_requests": 3,
        "weather_impact": 4.5,
        "previous_delay_count": 1,
        "risk_history": 4.6
    },
    {
        "code": "PRJ-IND-BRG-008",
        "name": "Chenab Rail Arch Viaduct Bridge (Package B Approaches)",
        "category": "Bridge",
        "location": "Jammu & Kashmir",
        "executing_agency": "Konkan Railway Corporation Ltd (KRCL)",
        "contractor_name": "Afcons Infrastructure",
        "project_cost": 1480.0,
        "planned_duration_months": 36,
        "start_date": "2023-07-01",
        "target_completion_date": "2026-07-01",
        "planned_progress": 50.0,
        "actual_progress": 43.5,
        "expenditure_percentage": 48.0,
        "resource_availability": 72.0,
        "material_availability": 70.0,
        "workforce_availability": 75.0,
        "contractor_performance": 76.0,
        "delay_days": 32,
        "milestone_completion_rate": 78.0,
        "change_requests": 2,
        "weather_impact": 6.0,
        "previous_delay_count": 1,
        "risk_history": 4.4
    },
    {
        "code": "PRJ-IND-AIR-010",
        "name": "Navi Mumbai International Airport (Phase 1 Cargo & MRO Terminal)",
        "category": "Airport",
        "location": "Maharashtra",
        "executing_agency": "CIDCO & Adani Airports Holding",
        "contractor_name": "Larsen & Toubro Ltd",
        "project_cost": 7200.0,
        "planned_duration_months": 42,
        "start_date": "2023-01-01",
        "target_completion_date": "2026-07-01",
        "planned_progress": 70.0,
        "actual_progress": 63.0,
        "expenditure_percentage": 68.0,
        "resource_availability": 79.0,
        "material_availability": 78.0,
        "workforce_availability": 80.0,
        "contractor_performance": 75.0,
        "delay_days": 28,
        "milestone_completion_rate": 80.0,
        "change_requests": 2,
        "weather_impact": 3.5,
        "previous_delay_count": 1,
        "risk_history": 3.8
    },
    {
        "code": "PRJ-IND-POW-015",
        "name": "Leh Mega 13GW Solar-Wind Renewable Energy Hybrid Grid",
        "category": "Power Infrastructure",
        "location": "Ladakh",
        "executing_agency": "Solar Energy Corporation of India (SECI)",
        "contractor_name": "Sterling and Wilson Renewable Energy",
        "project_cost": 21000.0,
        "planned_duration_months": 60,
        "start_date": "2023-04-01",
        "target_completion_date": "2028-04-01",
        "planned_progress": 35.0,
        "actual_progress": 29.0,
        "expenditure_percentage": 32.0,
        "resource_availability": 71.0,
        "material_availability": 69.0,
        "workforce_availability": 70.0,
        "contractor_performance": 74.0,
        "delay_days": 38,
        "milestone_completion_rate": 74.0,
        "change_requests": 2,
        "weather_impact": 7.0,
        "previous_delay_count": 1,
        "risk_history": 4.5
    },

    # --- 4. LOW RISK / ON TRACK PROJECTS (5+ projects) ---
    {
        "code": "PRJ-IND-HWY-004",
        "name": "Bangalore Satellite Town Ring Road (STRR - Dobbspet to Hoskote)",
        "category": "Highway",
        "location": "Karnataka",
        "executing_agency": "National Highways Authority of India (NHAI)",
        "contractor_name": "Ashoka Buildcon Ltd",
        "project_cost": 3250.0,
        "planned_duration_months": 30,
        "start_date": "2023-08-01",
        "target_completion_date": "2026-02-01",
        "planned_progress": 68.0,
        "actual_progress": 67.0,
        "expenditure_percentage": 66.5,
        "resource_availability": 92.0,
        "material_availability": 90.0,
        "workforce_availability": 94.0,
        "contractor_performance": 90.0,
        "delay_days": 4,
        "milestone_completion_rate": 96.0,
        "change_requests": 0,
        "weather_impact": 1.2,
        "previous_delay_count": 0,
        "risk_history": 1.5
    },
    {
        "code": "PRJ-IND-RAI-012",
        "name": "Eastern Dedicated Freight Corridor (Sonnagar - Dankuni PPP Section)",
        "category": "Railway",
        "location": "West Bengal",
        "executing_agency": "DFCCIL / Ministry of Railways",
        "contractor_name": "Tata Projects Ltd",
        "project_cost": 11800.0,
        "planned_duration_months": 48,
        "start_date": "2023-02-01",
        "target_completion_date": "2027-02-01",
        "planned_progress": 58.0,
        "actual_progress": 57.5,
        "expenditure_percentage": 57.0,
        "resource_availability": 94.0,
        "material_availability": 92.0,
        "workforce_availability": 95.0,
        "contractor_performance": 92.0,
        "delay_days": 2,
        "milestone_completion_rate": 98.0,
        "change_requests": 1,
        "weather_impact": 1.8,
        "previous_delay_count": 0,
        "risk_history": 1.2
    },
    {
        "code": "PRJ-IND-AIR-014",
        "name": "Noida International Airport (Jewar Phase 2 Runway & North Terminal)",
        "category": "Airport",
        "location": "Uttar Pradesh",
        "executing_agency": "Yamuna International Airport Pvt Ltd (YIAPL)",
        "contractor_name": "Tata Projects Limited",
        "project_cost": 5730.0,
        "planned_duration_months": 36,
        "start_date": "2023-09-01",
        "target_completion_date": "2026-09-01",
        "planned_progress": 48.0,
        "actual_progress": 49.0,
        "expenditure_percentage": 48.0,
        "resource_availability": 95.0,
        "material_availability": 96.0,
        "workforce_availability": 94.0,
        "contractor_performance": 94.0,
        "delay_days": 0,
        "milestone_completion_rate": 100.0,
        "change_requests": 1,
        "weather_impact": 1.0,
        "previous_delay_count": 0,
        "risk_history": 1.0
    },
    {
        "code": "PRJ-IND-URB-016",
        "name": "GIFT City Smart Automated Utility Tunnel & District Cooling Phase 3",
        "category": "Urban Development",
        "location": "Gujarat",
        "executing_agency": "Gujarat International Finance Tec-City Co.",
        "contractor_name": "Voltas - Sterling Wilson Consortium",
        "project_cost": 1650.0,
        "planned_duration_months": 24,
        "start_date": "2024-01-10",
        "target_completion_date": "2026-01-10",
        "planned_progress": 75.0,
        "actual_progress": 76.5,
        "expenditure_percentage": 73.0,
        "resource_availability": 96.0,
        "material_availability": 95.0,
        "workforce_availability": 98.0,
        "contractor_performance": 95.0,
        "delay_days": 0,
        "milestone_completion_rate": 100.0,
        "change_requests": 0,
        "weather_impact": 0.8,
        "previous_delay_count": 0,
        "risk_history": 0.9
    },
    {
        "code": "PRJ-IND-MET-017",
        "name": "Kochi Metro Phase 2 (JLN Stadium to Kakkanad Infopark Corridor)",
        "category": "Metro",
        "location": "Kerala",
        "executing_agency": "Kochi Metro Rail Limited (KMRL)",
        "contractor_name": "L&T Construction",
        "project_cost": 1957.0,
        "planned_duration_months": 36,
        "start_date": "2023-11-01",
        "target_completion_date": "2026-11-01",
        "planned_progress": 42.0,
        "actual_progress": 43.0,
        "expenditure_percentage": 41.5,
        "resource_availability": 91.0,
        "material_availability": 90.0,
        "workforce_availability": 92.0,
        "contractor_performance": 91.0,
        "delay_days": 0,
        "milestone_completion_rate": 97.0,
        "change_requests": 1,
        "weather_impact": 2.4,
        "previous_delay_count": 0,
        "risk_history": 1.4
    }
]

def seed_database():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    # Clear existing data to allow fresh seed
    db.query(Alert).delete()
    db.query(AnalysisLog).delete()
    db.query(Project).delete()
    db.commit()

    print(f"Seeding {len(SAMPLE_PROJECTS)} realistic infrastructure projects into SQLite...")

    for data in SAMPLE_PROJECTS:
        # Run prediction engine to initialize baseline health & risk
        analysis = prediction_engine.predict(data)
        
        project = Project(
            code=data["code"],
            name=data["name"],
            category=data["category"],
            location=data["location"],
            executing_agency=data["executing_agency"],
            contractor_name=data["contractor_name"],
            project_cost=data["project_cost"],
            planned_duration_months=data["planned_duration_months"],
            start_date=data["start_date"],
            target_completion_date=data["target_completion_date"],
            planned_progress=data["planned_progress"],
            actual_progress=data["actual_progress"],
            expenditure_percentage=data["expenditure_percentage"],
            resource_availability=data["resource_availability"],
            material_availability=data["material_availability"],
            workforce_availability=data["workforce_availability"],
            contractor_performance=data["contractor_performance"],
            delay_days=data["delay_days"],
            milestone_completion_rate=data["milestone_completion_rate"],
            change_requests=data["change_requests"],
            weather_impact=data["weather_impact"],
            previous_delay_count=data["previous_delay_count"],
            risk_history=data["risk_history"],
            risk_level=analysis["risk_level"],
            health_score=analysis["health_score"],
            predicted_delay_months=analysis["predicted_delay_months"],
            predicted_cost_overrun_percentage=analysis["predicted_cost_overrun_percentage"],
            confidence=analysis["confidence"],
            last_analyzed=datetime.datetime.utcnow()
        )
        db.add(project)
        db.flush()

        # Seed initial analysis log
        log = AnalysisLog(
            project_id=project.id,
            risk_level=analysis["risk_level"],
            confidence=analysis["confidence"],
            predicted_delay_months=analysis["predicted_delay_months"],
            predicted_cost_overrun_percentage=analysis["predicted_cost_overrun_percentage"],
            health_score=analysis["health_score"],
            risk_factors=json.dumps(analysis["risk_factors"]),
            recommendations=json.dumps(analysis["recommendations"]),
            timeline_projections=json.dumps(analysis["timeline_projections"]),
            created_at=datetime.datetime.utcnow()
        )
        db.add(log)

        # Seed alerts for Critical & High Risk projects
        if analysis["risk_level"] == "CRITICAL":
            alert = Alert(
                project_id=project.id,
                project_name=project.name,
                severity="CRITICAL",
                title=f"Critical Alert: {project.name}",
                message=f"Severe schedule deviation ({data['planned_progress'] - data['actual_progress']:.1f}%) and contractor performance deficit detected. Predicted delay: {analysis['predicted_delay_months']} months.",
                category="Schedule & Contractor",
                is_read=False,
                created_at=datetime.datetime.utcnow() - datetime.timedelta(hours=2)
            )
            db.add(alert)
        elif analysis["risk_level"] == "HIGH":
            alert = Alert(
                project_id=project.id,
                project_name=project.name,
                severity="WARNING",
                title=f"Warning: {project.name}",
                message=f"Resource availability constrained at {data['resource_availability']}%. Potential cost overrun of {analysis['predicted_cost_overrun_percentage']}%.",
                category="Resource & Cost",
                is_read=False,
                created_at=datetime.datetime.utcnow() - datetime.timedelta(hours=6)
            )
            db.add(alert)
        elif analysis["risk_level"] == "MEDIUM":
            alert = Alert(
                project_id=project.id,
                project_name=project.name,
                severity="WATCH",
                title=f"Watchlist: {project.name}",
                message=f"Moderate progress lag ({data['delay_days']} delay days). Keep under observation.",
                category="Milestones",
                is_read=False,
                created_at=datetime.datetime.utcnow() - datetime.timedelta(hours=14)
            )
            db.add(alert)

    db.commit()
    print("Database seeding completed successfully!")
    db.close()

if __name__ == "__main__":
    seed_database()
